dbt_project:
  outputs:
    dev:
      dbname: EcommerceDB
      host: localhost
      pass: postgres123
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
dbt_transformation:
  outputs:
    dev:
      dbname: postgres
      host: postgres_container
      pass: postgres123
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
